export const tags = [
  "Apartamento",
  "Alugados",
  "Demolição",
  "Ambientes pequenos",
  "Ambientes grandes",
  "Corporativo",
  "Varejo",
  "Roll-out",
  "Acessibilidade",
  "Crianças",
  "Minimalista",
  "Reformas",
  "Industrial",
  "Vigilância sanitária",
  "Estrutural",
  "Instalações",
  "Automação residencial",
];
