export const tags = [
  "apartamento",
  "alugados",
  "demolição",
  "ambientes pequenos",
  "ambientes grandes",
  "corporativo",
  "varejo",
  "roll-out",
  "acessibilidade",
  "crianças",
  "minimalista",
  "redormas",
  "industrial",
  "vigilância sanitária",
  "estrutural",
  "instalações",
  "automação residencial",
];
